### ISSUE TITLE
How have you encoded the TFRecords ?

### ISSUE THREAD

**Issue by IshrakHasin** [kongchen1992/deep-nrsfm#2]
I am trying to use this code for my project. I need to know its training is encoded or how to decode the TFRecords data?

**Comment by kongchen1992** [comment]
Thanks for your interest!  There are two raw vectors encoded in the TFRecords data: 1) points3d_raw and 2) points2d_raw.  The function __parse_function in motion_capture.py will give you a hint to decode the data.  For your convenience, I copied it there.  Please let me know if you have additional questions.

def _parse_function(example_proto):
    """Parses raw bytes into tensors."""
    features = {
        "points3d_raw": tf.FixedLenFeature((), tf.string, default_value=""),
        "points2d_raw": tf.FixedLenFeature((), tf.string, default_value=""),
    }
    parsed_features = tf.parse_single_example(example_proto, features)
    output_features = {
        "points3d": tf.reshape(
            tf.decode_raw(parsed_features["points3d_raw"], tf.float32),
            [NUM_POINTS, 3],
        ),
        "points2d": tf.reshape(
            tf.decode_raw(parsed_features["points2d_raw"], tf.float32),
            [NUM_POINTS, 2],
        ),
    }
    # Returns a tuple (features, labels)
    return output_features, 0

**Comment by WinstonDeng** [comment]
I'm trying to encode 2d point coordinates to tfdataset accroding to decode process but failed, so how to encode ? I need source code if it's convenience.
