### ISSUE TITLE
How to use camera as input

### ISSUE THREAD

**Issue by WinstonDeng** [kongchen1992/deep-nrsfm#4]
I'm trying to use your code for realtime, but don't know how to use camera as input.

**Comment by kongchen1992** [comment]
This work only takes 2D coordinates as input and estimate the 3D structure plus the camera as output.  So you cannot input the camera actually...

**Comment by WinstonDeng** [comment]
So how to use your model with my 2d points as input? Trans 2d coordinates into .train file？
