### ISSUE TITLE
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. 

### ISSUE THREAD

**Issue by WinstonDeng** [kongchen1992/deep-nrsfm#5]
I'm trying to use your model with 2d coordinates as input, so that I build this function to replace your eval_input_fn(filename, barch_size). The return of my function is same with yours, i.e. 

({'points3d': <tf.Tensor 'Reshape_1:0' shape=(32, 17, 3) dtype=float32>, 'points2d': <tf.Tensor 'Reshape:0' shape=(32, 17, 2) dtype=float32>}, <tf.Tensor 'Reshape_2:0' shape=(32,) dtype=int32>)

but never stop with warning : WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.

Do you have any idea to solve it?

## my code is here
 ‘’‘
         @param : keypoints2DList   is a list. 
          Shpae = 32*17*3. 
          keypoints2DList[ i , : , :2 ] is 2d coordinates of  frame i
          This function aims to build model input dataset from 2d coordinates, which is  to replace your 
  eval_input_fn
 ’‘’

def my_eval_input_fn(keypoints2DList):

      features={
          'points2d': tf.FixedLenFeature((), tf.float32, default_value=""),
          'points3d': tf.FixedLenFeature((), tf.float32, default_value=""),
      }

      keypoints2DList=np.array(keypoints2DList)
      features.update(points2d=tf.reshape(keypoints2DList[..., :2], [32, 17, 2]))
      features.update(points3d=tf.reshape(keypoints2DList, [32, 17, 3]))

      temp=[]
      for _ in range(32):
          temp.append(0)

      t = features, tf.reshape(temp, [32, ])

      return tuple(t)

**Comment by kongchen1992** [comment]
Thanks for you interest but I guess this warning is out of the scope of this project. You might want to google it and see why your code is shooting a warning. I would point you to read https://github.com/tensorflow/tensorflow/issues/11621.  

Thanks again your interest and I am closing this issue.
