### ISSUE TITLE
How to encode points coordinates to .train file?

### ISSUE THREAD

**Issue by WinstonDeng** [kongchen1992/deep-nrsfm#6]
I try my best to encode  points coordinates to .train file, but failed. What's the difference between your code and mine? Thanks for your attention. : )

 ```
for i in range(num):
     example = tf.train.Example(features=tf.train.Features(feature={
            "points3d_raw": tf.train.Feature(bytes_list=tf.train.BytesList(value=[keypoints2DList[i].tobytes()])),
            "points2d_raw": tf.train.Feature(bytes_list=tf.train.BytesList(value=[keypoints3DList[i].tobytes()])),
        }))
     writer.write(example.SerializeToString())
writer.close()
```

**Comment by kongchen1992** [comment]
What do you mean by "failed"?  Any error message?  Did you use "float32"?

**Comment by WinstonDeng** [comment]
Thanks for reading my comment! There were no error message but exit. However, I know where the problems are. The process of encode is definitely right.
