### ISSUE TITLE
How to set hparams when training model?

### ISSUE THREAD

**Issue by WinstonDeng** [kongchen1992/deep-nrsfm#7]
I reconstructed  training data from your **23.train**. The different is that my point number is 13 and yours is 31. But after training according to **train.sh** , my 13 points model doesn't perform as well as yours. So I suspect there are something wrong with my hparams settings. 

Does a change in the number of points affect model performance? If so,  which parameters need to be adjusted?

Thanks for your help!

**Comment by kongchen1992** [comment]
You definitely need to change the hparams because you are using less points.  I would recommend you to reduce the number of dictionary as well as the number of atoms in each dictionary. 

Cheers

**Comment by WinstonDeng** [comment]
Thanks a lot!
