### ISSUE TITLE
Where is the Visualization.ipynb

### ISSUE THREAD

**Issue by jfzhuang** [kongchen1992/deep-nrsfm#9]
Thanks for your excellent work and code release! After I run evaluate.sh, I want to visualize the results. I notice that I can use Visualization.ipynb for visualization but I can't find it in the release code. Did I miss something?

**Comment by kongchen1992** [comment]
Thanks for your interests! Yeah, it's my fault. I forgot to add that into the repository but you can copy code from here (http://www.cs.cmu.edu/~chenk/deep-nrsfm/Visualization.html) and create a notebook by yourself.  Let me know if you have additional issues, otherwise I will close this.
